export const ADD_TASK = "TODO/ADD_TASK";

export const REMOVE_TASK = "TODO/REMOVE_TASK";
export const COMPLETE_TASK = "TODO/COMPLETE_TASK";
export const SEARCH_DATE_TASK = "TODO/SEARCH_DATE_TASK";

export const SET_INPUT_TODO = "TODO/SET_INPUT_TODO"